# Generated by Django 5.0.1 on 2024-01-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(null=True, upload_to='brands/'),
        ),
    ]
