# Generated by Django 5.0.1 on 2024-01-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_category_description_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, default='defaultbrand.png', null=True, upload_to='brands/'),
        ),
    ]
