# Generated by Django 5.0.1 on 2024-01-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_brand_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='defaultbrand.png', null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='defaultbrand.png', null=True, upload_to='items/'),
        ),
    ]
