# Generated by Django 5.0.1 on 2024-01-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_popularitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(default='defaultbrand.png', upload_to='offers/')),
                ('is_star_offer', models.BooleanField(default=False)),
                ('validity_date', models.DateField()),
            ],
        ),
    ]
