# Generated by Django 5.0.1 on 2024-01-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_offer_created_offer_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='title',
            field=models.CharField(default='Catch the sale of today', max_length=255),
            preserve_default=False,
        ),
    ]
