# Generated by Django 5.0.1 on 2024-01-29 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_company'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Firm',
        ),
    ]
