# Generated by Django 5.0.1 on 2024-02-29 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_category_image_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularitems',
            name='validity_date',
            field=models.DateField(null=True),
        ),
    ]
